"""empty message

Revision ID: 03f96868ebb9
Revises: fe7200e4cbbf
Create Date: 2024-07-31 11:01:40.688551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f96868ebb9'
down_revision: Union[str, None] = 'fe7200e4cbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('design_is_agreed', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('value_is_agreed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'value_is_agreed')
    op.drop_column('works', 'design_is_agreed')
    # ### end Alembic commands ###
