"""add one column in table admins

Revision ID: 8ac02debbb45
Revises: 0699917ece68
Create Date: 2024-08-02 21:31:19.466937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac02debbb45'
down_revision: Union[str, None] = '0699917ece68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('is_main_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'is_main_admin')
    # ### end Alembic commands ###
